version: "3.3"
services:
  cassandra-3:
    image: cassandra:4.0.6
    container_name: cassandra-3
    hostname: cassandra-3
    ports:
      - "7000:7000"
    networks:
      tisya-net:
        ipv4_address: 172.16.1.33
    environment:
      - "CASSANDRA_CLUSTER_NAME=multidc-cluster"
      - "CASSANDRA_SEEDS=cassandra-3"
      - "CASSANDRA_NUM_TOKENS=4"
      - "CASSANDRA_DC=Bengaluru"
      - "CASSANDRA_RACK=Rack1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    volumes:
      - "./cassandra-3:/var/lib/cassandra"
  cassandra-4:
    image: cassandra:4.0.6
    container_name: cassandra-4
    hostname: cassandra-4
    networks:
      tisya-net:
        ipv4_address: 172.16.1.34
    environment:
      - "CASSANDRA_CLUSTER_NAME=multidc-cluster"
      - "CASSANDRA_SEEDS=cassandra-3"
      - "CASSANDRA_NUM_TOKENS=4"
      - "CASSANDRA_DC=NewYork"
      - "CASSANDRA_RACK=Rack1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    volumes:
      - "./cassandra-4:/var/lib/cassandra"
networks:
  tisya-net:
    external: true
