version: "3.3"
services:
  cassandra-1:
    image: cassandra:4.0.6
    container_name: cassandra-1
    hostname: cassandra-1
    ports:
      - "9041:9042"
    networks:
      tisya-net:
        ipv4_address: 172.16.1.31
    environment:
      - "CASSANDRA_CLUSTER_NAME=my-cluster"
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_NUM_TOKENS=4"
    volumes:
      - "./cassandra-1:/var/lib/cassandra"
  cassandra-2:
    image: cassandra:4.0.6
    container_name: cassandra-2 
    hostname: cassandra-2
    ports:
      - "9042:9042"
    networks:
      tisya-net:
        ipv4_address: 172.16.1.32
    environment:
      - "CASSANDRA_CLUSTER_NAME=my-cluster"
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_NUM_TOKENS=4"
    volumes:
      - "./cassandra-2:/var/lib/cassandra"
networks:
  tisya-net:
    external: true
